### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by cfoellmann**
This fixes up the UI.
The admin pages have some accessibility issues and with these changes behave like core pages. For better or worse.

### CODE REVIEW

**Comment by johnjamesjacoby** [comment]
Shoot. I just noticed this, after d84af672759e5739313d97ba388536530906127d

Will need to manually merge later, but I'll be sure to check this out. Thanks for this, and sorry it will take a bit longer to review.

**Comment by johnjamesjacoby** [comment]
Haven't forgotten about this; just have not made time to manually merge.

**Comment by cfoellmann** [comment]
I can rebase if you like!

**Comment by johnjamesjacoby** [comment]
> I can rebase if you like

That would be super helpful, but I know that's painful so I wouldn't ever ask you to. :+1:

**Comment by cfoellmann** [comment]
I did a rebase but give me some time to give it another look tomorrow.
Will ping you then. When I checked all rebase fixes

**Comment by johnjamesjacoby** [comment]
> Will ping you then

Thanks again!

**Comment by cfoellmann** [comment]
Fixed.

**Comment by cfoellmann** [comment]
@johnjamesjacoby *PING*

**Pull request merged**
